### ISSUE TITLE
Create a Website for this Repo

### ISSUE THREAD

**Issue by jfullstackdev** [ryanmcdermott/code-review-tips#6]
Hi there. 

Is there a website for this repo? 

Because if you don't have, well, this repo can simply be turned into a website right away. Others will discover this project in that website.

Steps:
1. Go to Settings and look for `GitHub Pages`, scroll down. That's almost at the bottom.

2. You will see there: `Branch:none`, so you should change that to `master` because you have a `README.md` file in the master repo. This will be your page. Click `Save` first.

3. Then click `Choose a theme`, you select a predefined theme of your site.

4. Visit your site now! The URL will be `https://ryanmcdermott.github.io/code-review-tips`. 

If you were amazed by that, simply read the documentation about GitHub Pages.

**Comment by ryanmcdermott** [comment]
Thanks for your input! I prefer to keep this as a README because there's one less link to navigate to and it lowers the friction to creating a PR if there's a spelling/grammar/code correction somebody wants to make!
